sessions_per_test: [10, 20, 30, 50] 
runs_per_test: 5 #  the average values from all the runs will be reported
transaction_file: ./test_queries.psql
db_config:
  host: localhost
  port: 5431
  db: mydb
  username: postgres
  password: secret