user_load_testing_config:
  concurrent_users: [10, 50, 100, 500]  
  nb_requests: 3 
  queries_file: /pg/user/test_queries.sql
app_load_testing_config:
  concurrent_instances: 10
  connection_pool_size: 128
  duration: 300
  load_script: tpcb-like
  protocol: prepared
db_config:
  host: localhost
  port: 5432
  db: pgbench
  username: postgres
  password: secret
