user_load_testing_config:
  concurrent_users: [10, 50, 100, 500]  
  nb_requests: 3 
  queries_file: ./test_queries.sql
db_config:
  host: localhost
  port: 5431
  db: mydb
  username: postgres
  password: secret
