sessions_per_test: [10, 100, 1000]  
runs_per_query: 3 #  how many times to run each query?
queries_file: ./test_queries.psql
db_config:
  host: localhost
  port: 5431
  db: mydb
  username: postgres
  password: secret